# Generated by Django 5.0.6 on 2024-05-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phones", "0002_inventory_last_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="color",
            field=models.CharField(
                choices=[("red", "Red"), ("black", "Black"), ("green", "Green")],
                default="Select an Option",
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
