# Generated by Django 5.0.6 on 2024-05-21 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phones", "0004_inventory_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="phone_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("build_date", models.DateField()),
                ("price", models.PositiveIntegerField()),
                ("last_modified", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="brand_name",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="build_date",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="last_modified",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="model",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="price",
        ),
        migrations.AddField(
            model_name="inventory",
            name="phone",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="phones.phone_info",
            ),
            preserve_default=False,
        ),
    ]
