# Generated by Django 5.0.6 on 2024-05-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("build_date", models.DateField()),
                ("price", models.PositiveIntegerField()),
                ("quantity", models.PositiveIntegerField()),
            ],
        ),
    ]
