# Generated by Django 5.0.6 on 2024-05-21 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="inventory",
        ),
    ]
